// src/lib/exportUtils.js
// PDF and Excel export helpers for DILG reports

import jsPDF from 'jspdf'
import 'jspdf-autotable'
import * as XLSX from 'xlsx'

// ── PDF Export ─────────────────────────────────────────────────
export function exportToPDF({ title, subtitle = 'Barangay Kayvaluganan · CY 2026', rows }) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text('Republic of the Philippines', doc.internal.pageSize.width / 2, 15, { align: 'center' })
  doc.text('Province of Batanes · Municipality of Basco', doc.internal.pageSize.width / 2, 21, { align: 'center' })

  doc.setFontSize(14)
  doc.setTextColor(11, 31, 58) // navy
  doc.setFont(undefined, 'bold')
  doc.text(title.toUpperCase(), doc.internal.pageSize.width / 2, 32, { align: 'center' })

  doc.setFontSize(10)
  doc.setFont(undefined, 'normal')
  doc.setTextColor(100)
  doc.text(subtitle, doc.internal.pageSize.width / 2, 39, { align: 'center' })

  // Divider
  doc.setDrawColor(11, 31, 58)
  doc.setLineWidth(0.5)
  doc.line(14, 43, doc.internal.pageSize.width - 14, 43)

  // Table
  doc.autoTable({
    startY: 48,
    head: [['Indicator', 'Value']],
    body: rows,
    headStyles: { fillColor: [11, 31, 58], textColor: 255, fontSize: 10 },
    bodyStyles: { fontSize: 10 },
    alternateRowStyles: { fillColor: [245, 248, 252] },
    margin: { left: 14, right: 14 },
  })

  // Footer
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by PROTECT v1.0 · ${new Date().toLocaleDateString('en-PH')} · Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    )
  }

  doc.save(`${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`)
}

// ── Residents PDF ──────────────────────────────────────────────
export function exportResidentsToPDF(residents) {
  const doc = new jsPDF({ orientation: 'landscape' })

  doc.setFontSize(14)
  doc.setFont(undefined, 'bold')
  doc.setTextColor(11, 31, 58)
  doc.text('RESIDENT MASTERLIST', doc.internal.pageSize.width / 2, 15, { align: 'center' })
  doc.setFontSize(10)
  doc.setFont(undefined, 'normal')
  doc.setTextColor(100)
  doc.text('Barangay Kayvaluganan · Basco, Batanes · CY 2026', doc.internal.pageSize.width / 2, 22, { align: 'center' })

  doc.autoTable({
    startY: 28,
    head: [['Res. ID', 'Last Name', 'First Name', 'Purok', 'Age', 'Sex', 'Civil Status', 'HH Head', 'PWD', 'Solo Parent', 'Senior']],
    body: residents.map(r => [
      r.resident_no, r.last_name, r.first_name, r.purok,
      r.age ?? '', r.sex, r.civil_status,
      r.is_household_head ? 'Yes' : 'No',
      r.is_pwd ? 'Yes' : 'No',
      r.is_solo_parent ? 'Yes' : 'No',
      r.is_senior_citizen ? 'Yes' : 'No',
    ]),
    headStyles: { fillColor: [13, 158, 140], textColor: 255, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [240, 253, 250] },
  })

  doc.save(`Resident_Masterlist_${new Date().toISOString().split('T')[0]}.pdf`)
}

// ── Excel Export ───────────────────────────────────────────────
export function exportResidentsToExcel(residents) {
  const ws = XLSX.utils.json_to_sheet(residents.map(r => ({
    'Resident No.': r.resident_no,
    'Last Name': r.last_name,
    'First Name': r.first_name,
    'Middle Name': r.middle_name || '',
    'Purok': r.purok,
    'Date of Birth': r.date_of_birth,
    'Age': r.age ?? '',
    'Sex': r.sex,
    'Civil Status': r.civil_status,
    'HH Head': r.is_household_head ? 'Yes' : 'No',
    'PWD': r.is_pwd ? 'Yes' : 'No',
    'PWD Type': r.pwd_type || '',
    'Solo Parent': r.is_solo_parent ? 'Yes' : 'No',
    'Senior Citizen': r.is_senior_citizen ? 'Yes' : 'No',
    'Monthly Income': r.monthly_income || 0,
    'Occupation': r.occupation || '',
    'Contact No.': r.contact_number || '',
  })))

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Residents')
  XLSX.writeFile(wb, `Resident_Masterlist_${new Date().toISOString().split('T')[0]}.xlsx`)
}

export function exportIncidentsToExcel(incidents) {
  const ws = XLSX.utils.json_to_sheet(incidents.map(i => ({
    'Case No.': i.case_no,
    'Incident Type': i.incident_type,
    'Purok': i.purok,
    'Date': i.incident_date,
    'Complainant': i.complainant || '',
    'Status': i.status,
  })))
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Incidents')
  XLSX.writeFile(wb, `Incident_Log_${new Date().toISOString().split('T')[0]}.xlsx`)
}

export function exportBeneficiariesToExcel(beneficiaries) {
  const ws = XLSX.utils.json_to_sheet(beneficiaries.map(b => ({
    'Name': b.name || `${b.residents?.first_name} ${b.residents?.last_name}`,
    'Resident No.': b.resident_no || b.residents?.resident_no || '',
    'Program': b.program || b.assistance_programs?.name || '',
    'Status': b.status,
    'Last Release': b.last_release_date || '',
    'Total Released (₱)': b.total_released || 0,
  })))
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Beneficiaries')
  XLSX.writeFile(wb, `Beneficiary_Registry_${new Date().toISOString().split('T')[0]}.xlsx`)
}
